import java.sql.*;
import javax.swing.JOptionPane;
import project.ConnectionProvider;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shayed
 */
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookIDTextField = new javax.swing.JTextField();
        bookNameTextField = new javax.swing.JTextField();
        bookAuthorTextField = new javax.swing.JTextField();
        bookGenreTextField = new javax.swing.JTextField();
        bookAddedDateTextField = new javax.swing.JTextField();
        addBookSaveButton = new javax.swing.JButton();
        addbookCloseButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(330, 215));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 168, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("Author");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 206, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("Genre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 244, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("Added Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 282, -1, -1));

        bookIDTextField.setBackground(new java.awt.Color(204, 204, 255));
        bookIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 128, 220, -1));

        bookNameTextField.setBackground(new java.awt.Color(204, 204, 255));
        bookNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bookNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 166, 220, -1));

        bookAuthorTextField.setBackground(new java.awt.Color(204, 204, 255));
        bookAuthorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAuthorTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bookAuthorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 204, 220, -1));

        bookGenreTextField.setBackground(new java.awt.Color(204, 204, 255));
        bookGenreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookGenreTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bookGenreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 242, 220, -1));

        bookAddedDateTextField.setBackground(new java.awt.Color(204, 204, 255));
        bookAddedDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAddedDateTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bookAddedDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 280, 220, -1));

        addBookSaveButton.setBackground(new java.awt.Color(0, 0, 153));
        addBookSaveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBookSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        addBookSaveButton.setText("Save");
        addBookSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookSaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addBookSaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        addbookCloseButton.setBackground(new java.awt.Color(255, 51, 51));
        addbookCloseButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addbookCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        addbookCloseButton.setText("Close");
        addbookCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookCloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addbookCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add Books.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDTextFieldActionPerformed

    private void bookAuthorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAuthorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookAuthorTextFieldActionPerformed

    private void bookGenreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookGenreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookGenreTextFieldActionPerformed

    private void addBookSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookSaveButtonActionPerformed
       
        String bookID = bookIDTextField.getText();
        String bookName = bookNameTextField.getText();
        String bookAuthor = bookAuthorTextField.getText();
        String bookGenre = bookGenreTextField.getText();
        String bookAddedDate = bookAddedDateTextField.getText();
        
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("INSERT INTO member VALUES('"+bookID+"','"+bookName+"','"+bookAuthor+"','"+bookGenre+")");
            JOptionPane.showMessageDialog(null,"Successfully Updated");
            setVisible(false);
            new AddBook().setVisible(true);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Somethig Went wrong!");
            setVisible(false);
            new AddBook().setVisible(true);
        }
        
    }//GEN-LAST:event_addBookSaveButtonActionPerformed

    private void bookAddedDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAddedDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookAddedDateTextFieldActionPerformed

    private void bookNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNameTextFieldActionPerformed

    private void addbookCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookCloseButtonActionPerformed
    setVisible(false);
    }//GEN-LAST:event_addbookCloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookSaveButton;
    private javax.swing.JButton addbookCloseButton;
    private javax.swing.JTextField bookAddedDateTextField;
    private javax.swing.JTextField bookAuthorTextField;
    private javax.swing.JTextField bookGenreTextField;
    private javax.swing.JTextField bookIDTextField;
    private javax.swing.JTextField bookNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
