import java.sql.*;
import javax.swing.JOptionPane;
import project.ConnectionProvider;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shayed
 */
public class NewMember extends javax.swing.JFrame {

    /**
     * Creates new form NewMember
     */
    public NewMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        memberIdTextField = new javax.swing.JTextField();
        memberNameTextField = new javax.swing.JTextField();
        memberAddressTextField = new javax.swing.JTextField();
        memberPhoneTextField = new javax.swing.JTextField();
        memberDataSaveButton = new javax.swing.JButton();
        memberCloseButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(330, 215));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        memberIdTextField.setBackground(new java.awt.Color(204, 204, 255));
        memberIdTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        memberIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberIdTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(memberIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 225, -1));

        memberNameTextField.setBackground(new java.awt.Color(204, 204, 255));
        memberNameTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        memberNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(memberNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 225, -1));

        memberAddressTextField.setBackground(new java.awt.Color(204, 204, 255));
        memberAddressTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(memberAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 225, -1));

        memberPhoneTextField.setBackground(new java.awt.Color(204, 204, 255));
        memberPhoneTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        memberPhoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberPhoneTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(memberPhoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 225, -1));

        memberDataSaveButton.setBackground(new java.awt.Color(0, 0, 204));
        memberDataSaveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        memberDataSaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        memberDataSaveButton.setText("Save");
        memberDataSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberDataSaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(memberDataSaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        memberCloseButton.setBackground(new java.awt.Color(255, 51, 51));
        memberCloseButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        memberCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        memberCloseButton.setText("Close");
        memberCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberCloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(memberCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add Member.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memberNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberNameTextFieldActionPerformed

    private void memberCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberCloseButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_memberCloseButtonActionPerformed

    private void memberDataSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberDataSaveButtonActionPerformed
        
        String memberId = memberIdTextField.getText();
        String memberName = memberNameTextField.getText();
        String memberAddress = memberAddressTextField.getText();
        String memberPhone = memberPhoneTextField.getText();
        
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("INSERT INTO book VALUES('"+memberId+"','"+memberName+"','"+memberAddress+"','"+memberPhone+"')");
            JOptionPane.showMessageDialog(null,"Successfully Updated");
            setVisible(false);
            new NewMember().setVisible(true);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Member already registered");
            setVisible(false);
            new NewMember().setVisible(true);
        }
    }//GEN-LAST:event_memberDataSaveButtonActionPerformed

    private void memberIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberIdTextFieldActionPerformed

    private void memberPhoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberPhoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberPhoneTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField memberAddressTextField;
    private javax.swing.JButton memberCloseButton;
    private javax.swing.JButton memberDataSaveButton;
    private javax.swing.JTextField memberIdTextField;
    private javax.swing.JTextField memberNameTextField;
    private javax.swing.JTextField memberPhoneTextField;
    // End of variables declaration//GEN-END:variables
}
